services:
  - type: web
    name: munkey-backend
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn core.wsgi:application --forwarded-allow-ips='*'"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: SIMPLE_JWT_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
